import Head from "next/head";
import { Inter } from "next/font/google";

import Container from "@/components/atoms/container";
import Header from "@/components/organisms/header";
import ActivitiesSection from "@/components/organisms/activities-section";
import SupportSection from "@/components/organisms/support-section";
import NewsSection from "@/components/organisms/news-section";

import CtaSection from "@/components/organisms/cta-section";
import { createClient } from "contentful";
import SectionTitle from "@/components/atoms/section-title";
import Divider from "@/components/atoms/divider";
import ActivitiesCard from "@/components/molecules/activities-card";
import Fade from "react-reveal/Fade";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: "activities" });

  return {
    props: {
      activities: res.items,
    },
  };
}

const inter = Inter({ subsets: ["latin"] });

export default function Home({ activities }) {
  const handleScroll = (e) => {
    e.preventDefault();
    const href = e.currentTarget.href;
    const targetId = href.replace(/.*\#/, "");
    const elem = document.getElementById(targetId);
    elem?.scrollIntoView({
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <Container>
          <Header />
          <CtaSection />
          <ActivitiesSection activities={activities} />
          <section>
            {/* <div className="my-10">
              <div className="min-w-96 max-w-[800px] mx-auto my-6 flex flex-col items-center">
                <SectionTitle>Nasze działania</SectionTitle>
                <Divider />
              </div>
              <div className="px- py-1 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-4 lg:px-0 lg:py-10">
                <div className="grid gap-6 row-gap-5 md:row-gap-8 sm:mx-auto lg:grid-cols-2">
                  <Fade bottom>
                    {activities.map((activity) => {
                      return (
                        <ActivitiesCard
                          img={activity.fields.thumbnail.fields.file.url}
                          title={
                            activity.fields.titlePl
                              ? activity.fields.titlePl
                              : ""
                          }
                          href={`/single-activity/${activity.fields.slug}`}
                        />
                      );
                    })}
                  </Fade>
                </div>
              </div>
            </div> */}
          </section>
          <SupportSection />
          <NewsSection />
        </Container>
      </div>
    </>
  );
}
